name = "panel-pin"
main = "panel-pin-worker.js"
compatibility_date = "2026-02-03"
routes = ["say23.jumvi.co/panel*", "say23.jumvi.co/auth*", "say23.jumvi.co/api/*"]

[[r2_buckets]]
binding = "PANEL_FILES"
bucket_name = "jumvi-panel-files"

[[d1_databases]]
binding = "JUMVI_DB"
database_name = "jumvi-auth"
database_id = "89292d9d-374d-4382-b1c7-a79069fb0843"

[vars]
COOKIE_DOMAIN = "say23.jumvi.co"
NODE_ENV = "production"
